language: go
sudo: false
go:
  - 1.6

before_script:
  - go vet .

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/vendor/bin:$PATH"

script:
  - make
  - go test .
